# Generated by Django 5.2 on 2025-05-04 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='expediente',
            field=models.CharField(default=1, max_length=20, unique=True, verbose_name='Número de expediente'),
            preserve_default=False,
        ),
    ]
