# Generated by Django 5.2 on 2025-05-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEnsayo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ensayo', models.IntegerField()),
                ('presiono_a', models.BooleanField()),
                ('tiempo_reaccion', models.FloatField(blank=True, null=True)),
                ('hubo_estimulo_negativo', models.BooleanField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
