# Generated by Django 5.2 on 2025-05-04 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimento', '0002_registroensayo_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroExperimentoCompleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('Pavloviana', 'Fase Pavloviana'), ('Instrumental', 'Fase Instrumental'), ('Extincion', 'Fase Extinción')], max_length=15)),
                ('numero_ensayo', models.IntegerField()),
                ('estimulo', models.CharField(choices=[('triangulo', 'Triángulo'), ('cuadrado', 'Cuadrado')], max_length=10)),
                ('respuesta', models.CharField(choices=[('tecla_espacio', 'Tecla Espacio'), ('timeout', 'Timeout')], max_length=15)),
                ('tiempo_reaccion_ms', models.FloatField(blank=True, null=True)),
                ('consecuencia', models.CharField(choices=[('sonido_aversivo', 'Sonido Aversivo'), ('sonido_neutro', 'Sonido Neutro'), ('ninguna', 'Ninguna')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
